// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace FeedFm.Internal {
	
	public enum FeedError : int {

		BadCredentials = 5,
		Forbidden = 6,
		SkipDenied = 7,
		NoMoreMusic = 9,
		PlayNotActive = 12,
		InvalidParameters = 15,
		MissingParameter = 16,
		MissingObject = 17,
		InternalError = 18,
		NotUS = 19,
		PlaybackStarted = 20,
		PlaybackComplete = 21

	}
}